### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by n8chz** [bashrc2/epicyon#5]
Freshly installed, following verbatim the instructions in README.md. Account creation seems to work, as evidenced by `accounts` folder. But attempts to log in with same password used in account creation come up 401. Also of note, 401 always comes up on the second try; first try just goes back to login form.

**Comment by bashrc2** [comment]
I think I know what this might be. If the password contains \n or \r then that is interpreted to be EOL or CR and removed.

**Comment by n8chz** [comment]
No line breaks or anything like that in the password. In this case I wiped clean (down to OS install) a server that had been a Friendica instance, and "recycled" Friendica username and password (associated with same domain name) that was already in my about:logins. The password is of the CamelCasePassPhrase variety, definitely no "special characters," even printable ones. Hmm, now I wonder whether Epicyon truncates long passwords...

Nope, pared it down to nine non-special characters. Same behavior.

**Comment by bashrc2** [comment]
Next stage is to enable debug. touch debug in the place where epicyon is installed and then reboot the daemon. That will create a far more detailed log. The look for the point at which you try to log in.

**Comment by bashrc2** [comment]
Another question would be whether there is any intermediate password handling system between you and the daemon, such as LDAP.
